import { useSession } from "next-auth/react";
import Head from "next/head";
import Nav from "~/components/Nav";
import SignInOutButton from "~/components/SignInOutButton";

import { api } from "~/utils/api";

export default function Home() {
  const { data: sessionData } = useSession();
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Grammar check</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#47567c] to-[#15162c]">
        <div className="md:items-left container flex flex-col items-center justify-center gap-5 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Welcome to{" "}
            <span className="text-[hsl(280,100%,70%)]">GrammarCheck</span>
          </h1>
          <p className="text-lg italic text-white md:text-2xl">
            Your home for Korean grammar challenges
          </p>
          <div className="flex flex-col items-center gap-2">
            <SignInOutButton data={sessionData} />
          </div>
        </div>
      </main>
    </>
  );
}

// function AuthShowcase() {
//   const { data: sessionData } = useSession();

//   const { data: secretMessage } = api.example.getSecretMessage.useQuery(
//     undefined, // no input
//     { enabled: sessionData?.user !== undefined },
//   );

//   return (
//     <div className="flex flex-col items-center justify-center gap-4">
//       <p className="text-center text-2xl text-white">
//         {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
//         {secretMessage && <span> - {secretMessage}</span>}
//       </p>
//       <SignInOutButton data={} />
//     </div>
//   );
// }
