import Head from "next/head";
import Nav from "~/components/Nav";

export default function Profile() {
  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#47567c] to-[#15162c] text-white">
        Hello liam
      </main>
    </>
  );
}
