import { useSession } from "next-auth/react";
import Head from "next/head";
import { useEffect, useState } from "react";
import GrammarInput from "~/components/GrammarInput";
import GridWithTitle from "~/components/GridWithTitle";
import SignInOutButton from "~/components/SignInOutButton";
import { api } from "~/utils/api";

export default function SignedInHome() {
  const { data: sessionData } = useSession();
  const completedChallenges = api.challenges.getAll.useQuery();

  const { isLoading, isError, isSuccess, data, error } =
    api.challenges.getGrammar.useQuery();

  const [grammarState, setGrammarState] = useState({
    id: 0,
    name: "",
  });
  const [hasCompleted, setHasCompleted] = useState(false);
  const hasUserCompletedGrammar = grammarState
    ? api.challenges.getGrammarHasBeenCompleted.useQuery({
        grammarId: grammarState.id,
      })
    : null;

  useEffect(() => {
    if (!data) return;

    if (data.id && data.grammar) {
      setGrammarState({
        id: data.id,
        name: data.grammar,
      });
    }
  }, [isSuccess, data]);

  useEffect(() => {
    if (!hasUserCompletedGrammar) return;

    setHasCompleted(Boolean(hasUserCompletedGrammar.data));
  }, [setHasCompleted, grammarState, hasUserCompletedGrammar]);

  return (
    <>
      <Head>
        <title>Grammar check</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-full flex-col items-center  bg-gradient-to-b from-[#47567c] to-[#15162c] text-white ">
        <div className="container flex min-h-screen max-w-max flex-col items-center justify-center gap-4">
          {data ? <GrammarInput grammar={data} /> : null}
          {completedChallenges.data && hasCompleted ? (
            <GridWithTitle title="Solutions" data={completedChallenges.data} />
          ) : null}
          <div className="flex flex-col items-center gap-2">
            <SignInOutButton data={sessionData} />
          </div>
        </div>
      </main>
    </>
  );
}
