import { useSession } from "next-auth/react";
import Head from "next/head";
import GrammarInput from "~/components/GrammarInput";
import GridWithTitle from "~/components/GridWithTitle";
import SignInOutButton from "~/components/SignInOutButton";
import { api } from "~/utils/api";

export default function SignedInHome() {
  const { data: sessionData } = useSession();
  const completed = api.challenges.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Grammar check</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-full flex-col items-center  bg-gradient-to-b from-[#47567c] to-[#15162c] text-white">
        <div className="container flex flex-col items-center justify-center gap-4">
          <GrammarInput />
          <GridWithTitle title="Solutions" data={completed.data} />
          <div className="flex flex-col items-center gap-2">
            <SignInOutButton data={sessionData} />
          </div>
        </div>
      </main>
    </>
  );
}
